source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'
use_frameworks!

target 'Hello-Lynx' do
  pod 'Lynx', '3.4.0', :subspecs => ['Framework']
  pod 'PrimJS', '2.14.0-rc.1', :subspecs => ['quickjs','napi']

  # this is where the missing classes live
  pod 'LynxService', '3.4.0', :subspecs => ['Image','Log','Http']

  # Image deps
  pod 'SDWebImage','5.15.5'
  pod 'SDWebImageWebPCoder','0.11.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      # Make sure pods don't fail the build on warnings
      config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
      # Use C++17
      config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++17'

      # Keep toolchain consistent
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] ||= '12.0'
    end
  end
end
