services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount for development (optional)
      - ./agents:/app/agents:ro
      # Mount for temporary files
      - tmp_data:/private/tmp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  # Optional: Add a database if needed in the future
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: tiktok_db
  #     POSTGRES_USER: tiktok_user
  #     POSTGRES_PASSWORD: tiktok_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

volumes:
  tmp_data:
  # postgres_data:
